export const balance = {
  technologyCosts: {
    tribal: { research: 1, materials: 1 },
    agricultural: { research: 10, materials: 5 },
    bronze: { research: 40, materials: 15 },
    classical: { research: 180, materials: 50 },
    medieval: { research: 800, materials: 180 },
    renaissance: { research: 4000, materials: 600 },
    industrial: { research: 20000, materials: 2000 },
  } as Record<string, { research: number; materials: number }>,
  populationGrowth: {
    baseFoodCost: 10,
    multiplier: 1.12,
    scalingBreakpoint: 20,
    laterMultiplier: 1.012,
    lateScalingBreakpoint: 400,
    lateMultiplier: 1.004,
  },
  settlements: { costGrowth: 1.25 },
  military: { recruitCostGrowth: 1.002 },
  conquest: {
    baseDefense: 40,
    defenseGrowth: 1.8,
    baseDurationSeconds: 180,
    minimumDurationSeconds: 15,
    maximumDurationSeconds: 600,
    minimumCasualtyRate: 0.02,
    victoryCasualtyFactor: 0.16,
    defeatCasualtyRate: 0.35,
    defeatRatioPenalty: 0.35,
    maximumCasualtyRate: 0.7,
    rewardTerritory: 'frontier',
  },
  eraRequirements: {
    agricultural: { population: 20 },
    bronze: { population: 50, territories: 2, settlements: 2 },
    classical: { population: 150, territories: 4, capacity: 200 },
    medieval: { population: 400, territories: 7, cities: 2, military: 700 },
    renaissance: {
      population: 1000,
      territories: 10,
      cities: 5,
      capacity: 1500,
      military: 6000,
    },
    industrial: {
      population: 2000,
      territories: 16,
      cities: 10,
      capacity: 2500,
      military: 40000,
    },
  },
  automaticGrowth: {
    intervalSeconds: 10,
    minimumIntervalSeconds: 0.5,
    defaultReservePercent: 10,
    reserveOptions: [0, 10, 25, 50],
  },
  statistics: { sampleIntervalSeconds: 30, maxSamples: 2000 },
  manualGathering: {
    food: { amount: 1, feature: 'manualGathering' },
    materials: { amount: 1, feature: 'materials' },
  } as Record<string, { amount: number; feature: string }>,
  tickMs: 100,
  renderMs: 250,
  autosaveMs: 10_000,
  maxOfflineSeconds: 8 * 60 * 60,
  offlineStepSeconds: 10,
  eventLimit: 100,
  saveVersion: 5,
};
