import type { GameEffect, ResourceCost, TechnologyDefinition } from '../types';
import { balance } from './config';

type Entry = {
  id: string;
  name: string;
  era: string;
  branch: string;
  x: number;
  y: number;
  research: number;
  materials?: number;
  prerequisites: string[];
  effects: GameEffect[];
  effectText: string;
  description?: string;
};
const production = (resource: string, value: number): GameEffect => ({
  type: 'productionMultiplier',
  resource,
  value,
});
const unitBonus = (unit: string, value: number): GameEffect => ({
  type: 'unitProductionMultiplier',
  unit,
  value,
});
const unlock = (id: string): GameEffect => ({ type: 'unlockUnit', id });
const feature = (id: string): GameEffect => ({ type: 'unlockFeature', id });
const interval = (value: number): GameEffect => ({
  type: 'populationGrowthIntervalMultiplier',
  value,
});
function technology(e: Entry): TechnologyDefinition {
  const scale = balance.technologyCosts[e.era] ?? { research: 1, materials: 1 };
  const cost: ResourceCost[] = [
    { resource: 'research', amount: e.research * scale.research },
  ];
  if (e.materials)
    cost.push({ resource: 'materials', amount: e.materials * scale.materials });
  return {
    id: e.id,
    name: e.name,
    era: e.era,
    branch: e.branch,
    treePosition: { x: e.x, y: e.y },
    prerequisites: e.prerequisites,
    effects: e.effects,
    effectText: e.effectText,
    description: e.description ?? e.effectText,
    cost,
    visibilityCondition: { type: 'featureUnlocked', featureId: 'research' },
    unlockCondition:
      e.era === 'tribal'
        ? { type: 'always' }
        : { type: 'eraReached', eraId: e.era },
  };
}
const entries: Entry[] = [
  {
    id: 'foraging',
    name: 'Foraging',
    era: 'tribal',
    branch: 'food',
    x: 0,
    y: 0,
    research: 8,
    prerequisites: [],
    effects: [production('food', 1.3)],
    effectText: '+30% Food production',
  },
  {
    id: 'toolMaking',
    name: 'Tool Making',
    era: 'tribal',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 18,
    materials: 10,
    prerequisites: ['foraging'],
    effects: [production('materials', 1.25)],
    effectText: '+25% Materials production',
  },
  {
    id: 'woodworking',
    name: 'Woodworking',
    era: 'tribal',
    branch: 'materials',
    x: 1,
    y: 2,
    research: 35,
    materials: 30,
    prerequisites: ['toolMaking'],
    effects: [production('materials', 1.5)],
    effectText: '+50% Materials production',
  },
  {
    id: 'language',
    name: 'Language',
    era: 'tribal',
    branch: 'knowledge',
    x: 2,
    y: 0,
    research: 8,
    prerequisites: [],
    effects: [production('research', 1.1)],
    effectText: '+10% Research · Knowledge path',
  },
  {
    id: 'knowledgeSharing',
    name: 'Knowledge Sharing',
    era: 'tribal',
    branch: 'knowledge',
    x: 2,
    y: 1,
    research: 22,
    prerequisites: ['language'],
    effects: [production('research', 1.25)],
    effectText: '+25% Research production',
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    era: 'tribal',
    branch: 'food',
    x: 0,
    y: 3,
    research: 75,
    materials: 40,
    prerequisites: ['knowledgeSharing'],
    effects: [unlock('farmer')],
    effectText: 'Unlock Farmer · Settled civilization',
  },
  {
    id: 'settledLife',
    name: 'Settled Life',
    era: 'agricultural',
    branch: 'society',
    x: 3,
    y: 0,
    research: 90,
    materials: 80,
    prerequisites: ['agriculture', 'woodworking'],
    effects: [feature('settlementPlanning')],
    effectText: 'Unlock population automation path',
  },
  {
    id: 'naturalGrowth',
    name: 'Natural Growth',
    era: 'agricultural',
    branch: 'society',
    x: 3,
    y: 1,
    research: 100,
    materials: 60,
    prerequisites: ['settledLife'],
    effects: [feature('autoPopulationGrowth')],
    effectText: 'Unlock Auto Growth · every 10 seconds',
  },
  {
    id: 'irrigation',
    name: 'Irrigation',
    era: 'agricultural',
    branch: 'food',
    x: 0,
    y: 1,
    research: 100,
    materials: 100,
    prerequisites: ['agriculture', 'settledLife'],
    effects: [unitBonus('farmer', 1.25)],
    effectText: '+25% Farmer production',
  },
  {
    id: 'animalHusbandry',
    name: 'Animal Husbandry',
    era: 'agricultural',
    branch: 'food',
    x: 0,
    y: 2,
    research: 130,
    materials: 100,
    prerequisites: ['agriculture', 'settledLife'],
    effects: [production('food', 1.25)],
    effectText: '+25% Food production',
  },
  {
    id: 'stoneworking',
    name: 'Stoneworking',
    era: 'agricultural',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 110,
    materials: 120,
    prerequisites: ['toolMaking', 'settledLife'],
    effects: [production('materials', 1.3)],
    effectText: '+30% Materials production',
  },
  {
    id: 'mining',
    name: 'Mining',
    era: 'agricultural',
    branch: 'materials',
    x: 1,
    y: 2,
    research: 150,
    materials: 150,
    prerequisites: ['stoneworking'],
    effects: [unlock('miner')],
    effectText: 'Unlock Miner',
  },
  {
    id: 'divisionOfLabor',
    name: 'Division of Labor',
    era: 'agricultural',
    branch: 'society',
    x: 1,
    y: 0,
    research: 70,
    materials: 60,
    prerequisites: ['toolMaking', 'knowledgeSharing'],
    effects: ['gatherer', 'woodcutter', 'thinker'].map((id) =>
      unitBonus(id, 1.1),
    ),
    effectText: '+10% production for all tier 1 units',
  },
  {
    id: 'recordKeeping',
    name: 'Record Keeping',
    era: 'agricultural',
    branch: 'knowledge',
    x: 2,
    y: 1,
    research: 100,
    materials: 80,
    prerequisites: ['knowledgeSharing', 'settledLife'],
    effects: [feature('statistics')],
    effectText: 'Unlock Statistics and population history',
  },
  {
    id: 'writing',
    name: 'Writing',
    era: 'agricultural',
    branch: 'knowledge',
    x: 2,
    y: 2,
    research: 160,
    materials: 100,
    prerequisites: ['recordKeeping'],
    effects: [production('research', 1.35)],
    effectText: '+35% Research · Written knowledge path',
  },
  {
    id: 'organizedSettlements',
    name: 'Organized Settlements',
    era: 'agricultural',
    branch: 'society',
    x: 3,
    y: 3,
    research: 180,
    materials: 160,
    prerequisites: ['naturalGrowth', 'recordKeeping'],
    effects: [interval(0.7)],
    effectText: 'Auto Growth interval −30% (10 → 7s)',
  },
  {
    id: 'metallurgy',
    name: 'Metallurgy',
    era: 'bronze',
    branch: 'materials',
    x: 1,
    y: 0,
    research: 250,
    materials: 250,
    prerequisites: ['mining'],
    effects: [production('materials', 1.35)],
    effectText: '+35% Materials production',
  },
  {
    id: 'bronzeWorking',
    name: 'Bronze Working',
    era: 'bronze',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 350,
    materials: 400,
    prerequisites: ['metallurgy', 'toolMaking'],
    effects: [unlock('workshop')],
    effectText: 'Unlock Workshop',
  },
  {
    id: 'wheel',
    name: 'Wheel',
    era: 'bronze',
    branch: 'materials',
    x: 0,
    y: 0,
    research: 200,
    materials: 200,
    prerequisites: ['woodworking', 'settledLife'],
    effects: [production('materials', 1.2)],
    effectText: '+20% Materials production',
  },
  {
    id: 'advancedAgriculture',
    name: 'Advanced Agriculture',
    era: 'bronze',
    branch: 'food',
    x: 0,
    y: 1,
    research: 300,
    materials: 350,
    prerequisites: ['irrigation', 'animalHusbandry'],
    effects: [unlock('farm')],
    effectText: 'Unlock Farm · +10% Farmer production per Farm',
  },
  {
    id: 'census',
    name: 'Census',
    era: 'bronze',
    branch: 'society',
    x: 3,
    y: 0,
    research: 220,
    materials: 180,
    prerequisites: ['writing', 'recordKeeping'],
    effects: [feature('populationDistribution')],
    effectText: 'Unlock detailed population distribution',
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    era: 'bronze',
    branch: 'knowledge',
    x: 2,
    y: 0,
    research: 250,
    materials: 180,
    prerequisites: ['writing'],
    effects: [production('research', 1.3)],
    effectText: '+30% Research production',
  },
  {
    id: 'construction',
    name: 'Construction',
    era: 'bronze',
    branch: 'materials',
    x: 1,
    y: 2,
    research: 300,
    materials: 400,
    prerequisites: ['stoneworking', 'woodworking'],
    effects: [
      production('materials', 1.2),
      { type: 'populationCostMultiplier', value: 0.9 },
    ],
    effectText: '+20% Materials · Growth Food cost −10%',
  },
  {
    id: 'formalEducation',
    name: 'Formal Education',
    era: 'bronze',
    branch: 'knowledge',
    x: 2,
    y: 1,
    research: 400,
    materials: 300,
    prerequisites: ['writing', 'mathematics'],
    effects: [unlock('scholar')],
    effectText: 'Unlock Scholar',
  },
  {
    id: 'engineering',
    name: 'Engineering',
    era: 'classical',
    branch: 'materials',
    x: 1,
    y: 0,
    research: 600,
    materials: 800,
    prerequisites: ['construction', 'mathematics'],
    effects: [production('materials', 1.4)],
    effectText: '+40% Materials production',
  },
  {
    id: 'philosophy',
    name: 'Philosophy',
    era: 'classical',
    branch: 'knowledge',
    x: 2,
    y: 0,
    research: 600,
    materials: 400,
    prerequisites: ['formalEducation', 'writing'],
    effects: [production('research', 1.4)],
    effectText: '+40% Research production',
  },
  {
    id: 'urbanPlanning',
    name: 'Urban Planning',
    era: 'classical',
    branch: 'society',
    x: 3,
    y: 0,
    research: 650,
    materials: 800,
    prerequisites: ['construction', 'census'],
    effects: [{ type: 'populationCostMultiplier', value: 0.9 }],
    effectText: 'Growth Food cost −10% · Urban growth path',
  },
  {
    id: 'institutionalLearning',
    name: 'Institutional Learning',
    era: 'classical',
    branch: 'knowledge',
    x: 2,
    y: 1,
    research: 900,
    materials: 700,
    prerequisites: ['formalEducation', 'philosophy'],
    effects: [unlock('academy')],
    effectText: 'Unlock Academy',
  },
  {
    id: 'craftsmanship',
    name: 'Craftsmanship',
    era: 'classical',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 650,
    materials: 600,
    prerequisites: ['bronzeWorking', 'divisionOfLabor'],
    effects: [unitBonus('workshop', 1.3)],
    effectText: '+30% Workshop production',
  },
  {
    id: 'urbanCommunities',
    name: 'Urban Communities',
    era: 'classical',
    branch: 'society',
    x: 3,
    y: 1,
    research: 750,
    materials: 650,
    prerequisites: ['urbanPlanning', 'organizedSettlements'],
    effects: [interval(4 / 7)],
    effectText: 'Auto Growth interval 7 → 4s',
  },
  {
    id: 'publicHealth',
    name: 'Public Health',
    era: 'classical',
    branch: 'society',
    x: 3,
    y: 2,
    research: 1000,
    materials: 900,
    prerequisites: ['urbanCommunities', 'philosophy'],
    effects: [interval(0.5)],
    effectText: 'Auto Growth interval 4 → 2s',
  },
];
export const technologies = entries.map(technology);
