import type { GameEffect, ResourceCost, TechnologyDefinition } from '../types';
import { balance } from './config';

type Entry = {
  id: string;
  name: string;
  era: string;
  branch: string;
  x: number;
  y: number;
  research: number;
  materials?: number;
  prerequisites: string[];
  effects: GameEffect[];
  effectText: string;
  description?: string;
};
const production = (resource: string, value: number): GameEffect => ({
  type: 'productionMultiplier',
  resource,
  value,
});
const unitBonus = (unit: string, value: number): GameEffect => ({
  type: 'unitProductionMultiplier',
  unit,
  value,
});
const unlock = (id: string): GameEffect => ({ type: 'unlockUnit', id });
const feature = (id: string): GameEffect => ({ type: 'unlockFeature', id });
const interval = (value: number): GameEffect => ({
  type: 'populationGrowthIntervalMultiplier',
  value,
});
function technology(e: Entry): TechnologyDefinition {
  const scale = balance.technologyCosts[e.era] ?? { research: 1, materials: 1 };
  const cost: ResourceCost[] = [
    { resource: 'research', amount: e.research * scale.research },
  ];
  if (e.materials)
    cost.push({ resource: 'materials', amount: e.materials * scale.materials });
  return {
    id: e.id,
    name: e.name,
    era: e.era,
    branch: e.branch,
    treePosition: { x: e.x, y: e.y },
    prerequisites: e.prerequisites,
    effects: e.effects,
    effectText: e.effectText,
    description: e.description ?? e.effectText,
    cost,
    visibilityCondition: { type: 'featureUnlocked', featureId: 'research' },
    unlockCondition:
      e.era === 'tribal'
        ? { type: 'always' }
        : { type: 'eraReached', eraId: e.era },
  };
}
const entries: Entry[] = [
  {
    id: 'foraging',
    name: 'Foraging',
    era: 'tribal',
    branch: 'food',
    x: 0,
    y: 0,
    research: 8,
    prerequisites: [],
    effects: [production('food', 1.3)],
    effectText: '+30% Food production',
  },
  {
    id: 'toolMaking',
    name: 'Tool Making',
    era: 'tribal',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 18,
    materials: 10,
    prerequisites: ['foraging'],
    effects: [production('materials', 1.25)],
    effectText: '+25% Materials production',
  },
  {
    id: 'woodworking',
    name: 'Woodworking',
    era: 'tribal',
    branch: 'materials',
    x: 1,
    y: 2,
    research: 35,
    materials: 30,
    prerequisites: ['toolMaking'],
    effects: [production('materials', 1.5)],
    effectText: '+50% Materials production',
  },
  {
    id: 'language',
    name: 'Language',
    era: 'tribal',
    branch: 'knowledge',
    x: 2,
    y: 0,
    research: 8,
    prerequisites: [],
    effects: [production('research', 1.1)],
    effectText: '+10% Research · Knowledge path',
  },
  {
    id: 'knowledgeSharing',
    name: 'Knowledge Sharing',
    era: 'tribal',
    branch: 'knowledge',
    x: 2,
    y: 1,
    research: 22,
    prerequisites: ['language'],
    effects: [production('research', 1.25)],
    effectText: '+25% Research production',
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    era: 'tribal',
    branch: 'food',
    x: 0,
    y: 3,
    research: 75,
    materials: 40,
    prerequisites: ['knowledgeSharing'],
    effects: [unlock('farmer')],
    effectText: 'Unlock Farmer · Settled civilization',
  },
  {
    id: 'settledLife',
    name: 'Settled Life',
    era: 'agricultural',
    branch: 'society',
    x: 3,
    y: 0,
    research: 90,
    materials: 80,
    prerequisites: ['agriculture', 'woodworking'],
    effects: [feature('settlementPlanning'), feature('settlements')],
    effectText: 'Unlock Settlements · Population automation path',
  },
  {
    id: 'naturalGrowth',
    name: 'Natural Growth',
    era: 'agricultural',
    branch: 'society',
    x: 3,
    y: 1,
    research: 100,
    materials: 60,
    prerequisites: ['settledLife'],
    effects: [feature('autoPopulationGrowth')],
    effectText: 'Unlock Auto Growth · every 10 seconds',
  },
  {
    id: 'irrigation',
    name: 'Irrigation',
    era: 'agricultural',
    branch: 'food',
    x: 0,
    y: 1,
    research: 100,
    materials: 100,
    prerequisites: ['agriculture', 'settledLife'],
    effects: [unitBonus('farmer', 1.25)],
    effectText: '+25% Farmer production',
  },
  {
    id: 'animalHusbandry',
    name: 'Animal Husbandry',
    era: 'agricultural',
    branch: 'food',
    x: 0,
    y: 2,
    research: 130,
    materials: 100,
    prerequisites: ['agriculture', 'settledLife'],
    effects: [production('food', 1.25)],
    effectText: '+25% Food production',
  },
  {
    id: 'stoneworking',
    name: 'Stoneworking',
    era: 'agricultural',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 110,
    materials: 120,
    prerequisites: ['toolMaking', 'settledLife'],
    effects: [production('materials', 1.3)],
    effectText: '+30% Materials production',
  },
  {
    id: 'mining',
    name: 'Mining',
    era: 'agricultural',
    branch: 'materials',
    x: 1,
    y: 2,
    research: 150,
    materials: 150,
    prerequisites: ['stoneworking'],
    effects: [unlock('miner')],
    effectText: 'Unlock Miner',
  },
  {
    id: 'divisionOfLabor',
    name: 'Division of Labor',
    era: 'agricultural',
    branch: 'society',
    x: 1,
    y: 0,
    research: 70,
    materials: 60,
    prerequisites: ['toolMaking', 'knowledgeSharing'],
    effects: ['gatherer', 'woodcutter', 'thinker'].map((id) =>
      unitBonus(id, 1.1),
    ),
    effectText: '+10% production for all tier 1 units',
  },
  {
    id: 'recordKeeping',
    name: 'Record Keeping',
    era: 'agricultural',
    branch: 'knowledge',
    x: 2,
    y: 1,
    research: 100,
    materials: 80,
    prerequisites: ['knowledgeSharing', 'settledLife'],
    effects: [feature('statistics')],
    effectText: 'Unlock Statistics and population history',
  },
  {
    id: 'writing',
    name: 'Writing',
    era: 'agricultural',
    branch: 'knowledge',
    x: 2,
    y: 2,
    research: 160,
    materials: 100,
    prerequisites: ['recordKeeping'],
    effects: [production('research', 1.35)],
    effectText: '+35% Research · Written knowledge path',
  },
  {
    id: 'organizedSettlements',
    name: 'Organized Settlements',
    era: 'agricultural',
    branch: 'society',
    x: 3,
    y: 3,
    research: 180,
    materials: 160,
    prerequisites: ['naturalGrowth', 'recordKeeping'],
    effects: [interval(0.7)],
    effectText: 'Auto Growth interval −30% (10 → 7s)',
  },
  {
    id: 'metallurgy',
    name: 'Metallurgy',
    era: 'bronze',
    branch: 'materials',
    x: 1,
    y: 0,
    research: 250,
    materials: 250,
    prerequisites: ['mining'],
    effects: [production('materials', 1.35)],
    effectText: '+35% Materials production',
  },
  {
    id: 'bronzeWorking',
    name: 'Bronze Working',
    era: 'bronze',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 350,
    materials: 400,
    prerequisites: ['metallurgy', 'toolMaking'],
    effects: [unlock('workshop')],
    effectText: 'Unlock Workshop',
  },
  {
    id: 'wheel',
    name: 'Wheel',
    era: 'bronze',
    branch: 'materials',
    x: 0,
    y: 0,
    research: 200,
    materials: 200,
    prerequisites: ['woodworking', 'settledLife'],
    effects: [production('materials', 1.2)],
    effectText: '+20% Materials production',
  },
  {
    id: 'advancedAgriculture',
    name: 'Advanced Agriculture',
    era: 'bronze',
    branch: 'food',
    x: 0,
    y: 1,
    research: 300,
    materials: 350,
    prerequisites: ['irrigation', 'animalHusbandry'],
    effects: [unlock('farm')],
    effectText: 'Unlock Farm · +10% Farmer production per Farm',
  },
  {
    id: 'census',
    name: 'Census',
    era: 'bronze',
    branch: 'society',
    x: 3,
    y: 0,
    research: 220,
    materials: 180,
    prerequisites: ['writing', 'recordKeeping'],
    effects: [feature('populationDistribution')],
    effectText: 'Unlock detailed population distribution',
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    era: 'bronze',
    branch: 'knowledge',
    x: 2,
    y: 0,
    research: 250,
    materials: 180,
    prerequisites: ['writing'],
    effects: [production('research', 1.3)],
    effectText: '+30% Research production',
  },
  {
    id: 'construction',
    name: 'Construction',
    era: 'bronze',
    branch: 'materials',
    x: 1,
    y: 2,
    research: 300,
    materials: 400,
    prerequisites: ['stoneworking', 'woodworking'],
    effects: [
      { type: 'settlementCostMultiplier', resource: 'materials', value: 0.8 },
      production('materials', 1.2),
      { type: 'populationCostMultiplier', value: 0.9 },
    ],
    effectText: '+20% Materials · −20% settlement Materials cost',
  },
  {
    id: 'formalEducation',
    name: 'Formal Education',
    era: 'bronze',
    branch: 'knowledge',
    x: 2,
    y: 1,
    research: 400,
    materials: 300,
    prerequisites: ['writing', 'mathematics'],
    effects: [unlock('scholar')],
    effectText: 'Unlock Scholar',
  },
  {
    id: 'engineering',
    name: 'Engineering',
    era: 'classical',
    branch: 'materials',
    x: 1,
    y: 0,
    research: 600,
    materials: 800,
    prerequisites: ['construction', 'mathematics'],
    effects: [production('materials', 1.4)],
    effectText: '+40% Materials production',
  },
  {
    id: 'philosophy',
    name: 'Philosophy',
    era: 'classical',
    branch: 'knowledge',
    x: 2,
    y: 0,
    research: 600,
    materials: 400,
    prerequisites: ['formalEducation', 'writing'],
    effects: [production('research', 1.4)],
    effectText: '+40% Research production',
  },
  {
    id: 'urbanPlanning',
    name: 'Urban Planning',
    era: 'classical',
    branch: 'society',
    x: 3,
    y: 0,
    research: 650,
    materials: 800,
    prerequisites: ['construction', 'census'],
    effects: [
      { type: 'settlementCapacityMultiplier', value: 1.25 },
      { type: 'populationCostMultiplier', value: 0.9 },
    ],
    effectText: '+25% settlement capacity · −10% growth cost',
  },
  {
    id: 'institutionalLearning',
    name: 'Institutional Learning',
    era: 'classical',
    branch: 'knowledge',
    x: 2,
    y: 1,
    research: 900,
    materials: 700,
    prerequisites: ['formalEducation', 'philosophy'],
    effects: [unlock('academy')],
    effectText: 'Unlock Academy',
  },
  {
    id: 'craftsmanship',
    name: 'Craftsmanship',
    era: 'classical',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 650,
    materials: 600,
    prerequisites: ['bronzeWorking', 'divisionOfLabor'],
    effects: [unitBonus('workshop', 1.3)],
    effectText: '+30% Workshop production',
  },
  {
    id: 'urbanCommunities',
    name: 'Urban Communities',
    era: 'classical',
    branch: 'society',
    x: 3,
    y: 1,
    research: 750,
    materials: 650,
    prerequisites: ['urbanPlanning', 'organizedSettlements'],
    effects: [interval(4 / 7)],
    effectText: 'Auto Growth interval 7 → 4s',
  },
  {
    id: 'publicHealth',
    name: 'Public Health',
    era: 'classical',
    branch: 'society',
    x: 3,
    y: 2,
    research: 1000,
    materials: 900,
    prerequisites: ['urbanCommunities', 'philosophy'],
    effects: [interval(0.5)],
    effectText: 'Auto Growth interval 4 → 2s',
  },
  {
    id: 'villageOrganization',
    name: 'Village Organization',
    era: 'agricultural',
    branch: 'society',
    x: 3,
    y: 4,
    research: 90,
    materials: 180,
    prerequisites: ['settledLife'],
    effects: [],
    effectText: 'Unlock Town',
  },
  {
    id: 'organizedWarfare',
    name: 'Organized Warfare',
    era: 'agricultural',
    branch: 'society',
    x: 3,
    y: 5,
    research: 180,
    materials: 200,
    prerequisites: ['settledLife', 'divisionOfLabor'],
    effects: [feature('military'), feature('territory')],
    effectText: 'Unlock Military \u00b7 Territory campaigns',
  },
  {
    id: 'archery',
    name: 'Archery',
    era: 'bronze',
    branch: 'society',
    x: 3,
    y: 4,
    research: 180,
    materials: 150,
    prerequisites: ['bronzeWorking'],
    effects: [],
    effectText: 'Unlock Archer',
  },
  {
    id: 'aqueducts',
    name: 'Aqueducts',
    era: 'classical',
    branch: 'society',
    x: 3,
    y: 4,
    research: 220,
    materials: 350,
    prerequisites: ['urbanPlanning', 'engineering'],
    effects: [
      { type: 'settlementCapacityMultiplier', settlement: 'town', value: 1.5 },
      { type: 'settlementCapacityMultiplier', settlement: 'city', value: 1.5 },
    ],
    effectText: '+50% Town and City capacity',
  },
  {
    id: 'classicalArmy',
    name: 'Classical Army',
    era: 'classical',
    branch: 'society',
    x: 3,
    y: 5,
    research: 200,
    materials: 300,
    prerequisites: ['bronzeWorking', 'construction', 'census'],
    effects: [],
    effectText: 'Unlock Heavy Infantry',
  },
  {
    id: 'feudalOrganization',
    name: 'Feudal Organization',
    era: 'medieval',
    branch: 'society',
    x: 3,
    y: 0,
    research: 180,
    materials: 250,
    prerequisites: ['classicalArmy', 'urbanCommunities'],
    effects: [{ type: 'militaryPowerMultiplier', value: 1.15 }],
    effectText: 'Unlock Knight \u00b7 +15% Military Power',
  },
  {
    id: 'fortifications',
    name: 'Fortifications',
    era: 'medieval',
    branch: 'society',
    x: 3,
    y: 1,
    research: 180,
    materials: 400,
    prerequisites: ['feudalOrganization', 'engineering'],
    effects: [{ type: 'militaryCasualtyMultiplier', value: 0.65 }],
    effectText: '\u221235% campaign casualties',
  },
  {
    id: 'heavyPlow',
    name: 'Heavy Plow',
    era: 'medieval',
    branch: 'food',
    x: 0,
    y: 0,
    research: 160,
    materials: 240,
    prerequisites: ['advancedAgriculture', 'engineering'],
    effects: [production('food', 1.6)],
    effectText: '+60% Food production',
  },
  {
    id: 'guilds',
    name: 'Guilds',
    era: 'medieval',
    branch: 'materials',
    x: 1,
    y: 0,
    research: 190,
    materials: 300,
    prerequisites: ['craftsmanship'],
    effects: [production('materials', 1.6)],
    effectText: '+60% Materials production',
  },
  {
    id: 'universities',
    name: 'Universities',
    era: 'medieval',
    branch: 'knowledge',
    x: 2,
    y: 0,
    research: 220,
    materials: 300,
    prerequisites: ['institutionalLearning', 'philosophy'],
    effects: [production('research', 1.6)],
    effectText: '+60% Research production',
  },
  {
    id: 'civilAdministration',
    name: 'Civil Administration',
    era: 'medieval',
    branch: 'society',
    x: 3,
    y: 2,
    research: 230,
    materials: 300,
    prerequisites: ['feudalOrganization', 'census'],
    effects: [{ type: 'settlementCapacityMultiplier', value: 1.3 }],
    effectText: '+30% settlement capacity',
  },
  {
    id: 'professionalArmy',
    name: 'Professional Army',
    era: 'medieval',
    branch: 'society',
    x: 3,
    y: 3,
    research: 260,
    materials: 350,
    prerequisites: ['feudalOrganization', 'fortifications'],
    effects: [{ type: 'militaryPowerMultiplier', value: 1.5 }],
    effectText: '+50% Military Power',
  },
  {
    id: 'masonry',
    name: 'Masonry',
    era: 'medieval',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 180,
    materials: 350,
    prerequisites: ['guilds', 'construction'],
    effects: [
      { type: 'settlementCostMultiplier', resource: 'materials', value: 0.7 },
    ],
    effectText: '\u221230% settlement Materials cost',
  },
  {
    id: 'longDistanceTrade',
    name: 'Long Distance Trade',
    era: 'medieval',
    branch: 'materials',
    x: 1,
    y: 2,
    research: 240,
    materials: 300,
    prerequisites: ['guilds', 'civilAdministration'],
    effects: [production('materials', 1.2)],
    effectText: '+20% Materials \u00b7 Trade knowledge',
  },
  {
    id: 'sanitation',
    name: 'Sanitation',
    era: 'medieval',
    branch: 'society',
    x: 3,
    y: 4,
    research: 220,
    materials: 280,
    prerequisites: ['aqueducts', 'publicHealth'],
    effects: [
      { type: 'settlementCapacityMultiplier', value: 1.2 },
      { type: 'populationCostMultiplier', value: 0.85 },
    ],
    effectText: '+20% capacity \u00b7 \u221215% growth cost',
  },
  {
    id: 'printingPress',
    name: 'Printing Press',
    era: 'renaissance',
    branch: 'knowledge',
    x: 2,
    y: 0,
    research: 200,
    materials: 300,
    prerequisites: ['universities', 'longDistanceTrade'],
    effects: [production('research', 1.8)],
    effectText: '+80% Research production',
  },
  {
    id: 'humanism',
    name: 'Humanism',
    era: 'renaissance',
    branch: 'knowledge',
    x: 2,
    y: 1,
    research: 200,
    materials: 200,
    prerequisites: ['printingPress', 'philosophy'],
    effects: [
      production('research', 1.35),
      { type: 'populationCostMultiplier', value: 0.85 },
    ],
    effectText: '+35% Research \u00b7 \u221215% growth cost',
  },
  {
    id: 'navigation',
    name: 'Navigation',
    era: 'renaissance',
    branch: 'society',
    x: 3,
    y: 0,
    research: 230,
    materials: 320,
    prerequisites: ['longDistanceTrade', 'mathematics'],
    effects: [{ type: 'campaignDurationMultiplier', value: 0.8 }],
    effectText: '\u221220% campaign duration \u00b7 Navigation knowledge',
  },
  {
    id: 'gunpowder',
    name: 'Gunpowder',
    era: 'renaissance',
    branch: 'society',
    x: 3,
    y: 1,
    research: 260,
    materials: 400,
    prerequisites: ['professionalArmy', 'guilds'],
    effects: [],
    effectText: 'Unlock Musketeer',
  },
  {
    id: 'banking',
    name: 'Banking',
    era: 'renaissance',
    branch: 'materials',
    x: 1,
    y: 0,
    research: 220,
    materials: 320,
    prerequisites: ['longDistanceTrade', 'civilAdministration'],
    effects: [
      { type: 'settlementCostMultiplier', resource: 'materials', value: 0.85 },
    ],
    effectText: '\u221215% settlement Materials cost \u00b7 Banking knowledge',
  },
  {
    id: 'scientificMethod',
    name: 'Scientific Method',
    era: 'renaissance',
    branch: 'knowledge',
    x: 2,
    y: 2,
    research: 320,
    materials: 400,
    prerequisites: ['printingPress', 'humanism'],
    effects: [production('research', 2)],
    effectText: '\u00d72 Research production',
  },
  {
    id: 'advancedUrbanPlanning',
    name: 'Advanced Urban Planning',
    era: 'renaissance',
    branch: 'society',
    x: 3,
    y: 2,
    research: 280,
    materials: 450,
    prerequisites: ['civilAdministration', 'sanitation'],
    effects: [{ type: 'settlementCapacityMultiplier', value: 1.4 }],
    effectText: 'Unlock Metropolis \u00b7 +40% capacity',
  },
  {
    id: 'earlyIndustry',
    name: 'Early Industry',
    era: 'renaissance',
    branch: 'materials',
    x: 1,
    y: 1,
    research: 280,
    materials: 450,
    prerequisites: ['guilds', 'banking'],
    effects: [production('materials', 1.5)],
    effectText: '+50% Materials \u00b7 Industrial path',
  },
  {
    id: 'steamPower',
    name: 'Steam Power',
    era: 'renaissance',
    branch: 'materials',
    x: 1,
    y: 2,
    research: 380,
    materials: 600,
    prerequisites: ['earlyIndustry', 'scientificMethod'],
    effects: [production('materials', 1.5)],
    effectText: '+50% Materials \u00b7 Industrial prerequisite',
  },
  {
    id: 'mechanization',
    name: 'Mechanization',
    era: 'renaissance',
    branch: 'food',
    x: 0,
    y: 3,
    research: 420,
    materials: 650,
    prerequisites: ['steamPower', 'heavyPlow'],
    effects: [production('food', 1.5)],
    effectText: '+50% Food \u00b7 Industrial prerequisite',
  },
  {
    id: 'factories',
    name: 'Factories',
    era: 'industrial',
    branch: 'materials',
    x: 1,
    y: 0,
    research: 220,
    materials: 500,
    prerequisites: ['mechanization', 'steamPower'],
    effects: [
      unlock('factory'),
      unlock('industrialFarm'),
      unlock('laboratory'),
    ],
    effectText: 'Unlock industrial production tiers',
  },
];
export const technologies = entries.map(technology);
