import type { ProductionUnitDefinition } from '../types';

/** Upgrade quantities, costs and rates live here. The engine never names a specific unit. */
export const units: ProductionUnitDefinition[] = [
  {
    id: 'gatherer',
    name: 'Gatherer',
    description: 'Find food in the wild.',
    category: 'food',
    tier: 1,
    populationCost: 1,
    baseProduction: [{ resource: 'food', amount: 0.5 }],
    unlockCondition: { type: 'featureUnlocked', featureId: 'jobs' },
    legacyJobs: ['gatherer', 'farmer'],
  },
  {
    id: 'farmer',
    name: 'Farmer',
    description: 'Cultivate a reliable food supply together.',
    category: 'food',
    tier: 2,
    upgradeFrom: { unitId: 'gatherer', amount: 5 },
    costs: [
      { resource: 'materials', amount: 20 },
      { resource: 'food', amount: 50 },
    ],
    baseProduction: [{ resource: 'food', amount: 4 }],
    unlockCondition: { type: 'technologyOwned', technologyId: 'agriculture' },
    visibilityCondition: { type: 'populationAtLeast', value: 5 },
  },
  {
    id: 'farm',
    name: 'Farm',
    description: 'Organized fields help Farmers work more efficiently.',
    category: 'food',
    tier: 3,
    upgradeFrom: { unitId: 'farmer', amount: 4 },
    costs: [
      { resource: 'materials', amount: 100 },
      { resource: 'food', amount: 250 },
    ],
    baseProduction: [{ resource: 'food', amount: 20 }],
    effects: [
      {
        type: 'unitProductionMultiplier',
        unit: 'farmer',
        resource: 'food',
        value: 1.1,
      },
    ],
    unlockCondition: { type: 'never' },
  },
  {
    id: 'industrialFarm',
    name: 'Industrial Farm',
    description: 'Agriculture at an industrial scale.',
    category: 'food',
    tier: 4,
    upgradeFrom: { unitId: 'farm', amount: 5 },
    costs: [
      { resource: 'materials', amount: 4000 },
      { resource: 'food', amount: 5000 },
    ],
    baseProduction: [{ resource: 'food', amount: 150 }],
    unlockCondition: { type: 'never' },
  },
  {
    id: 'woodcutter',
    name: 'Woodcutter',
    description: 'Gather wood and useful materials.',
    category: 'materials',
    tier: 1,
    populationCost: 1,
    baseProduction: [{ resource: 'materials', amount: 0.5 }],
    unlockCondition: { type: 'featureUnlocked', featureId: 'jobs' },
    legacyJobs: ['woodcutter'],
  },
  {
    id: 'miner',
    name: 'Miner',
    description:
      'Turn a team of Woodcutters into specialized material producers.',
    category: 'materials',
    tier: 2,
    upgradeFrom: { unitId: 'woodcutter', amount: 5 },
    costs: [
      { resource: 'materials', amount: 30 },
      { resource: 'food', amount: 40 },
    ],
    baseProduction: [{ resource: 'materials', amount: 4 }],
    unlockCondition: { type: 'technologyOwned', technologyId: 'woodworking' },
    visibilityCondition: {
      type: 'technologyOwned',
      technologyId: 'toolMaking',
    },
  },
  {
    id: 'workshop',
    name: 'Workshop',
    description: 'Coordinate skilled material production.',
    category: 'materials',
    tier: 3,
    upgradeFrom: { unitId: 'miner', amount: 4 },
    costs: [
      { resource: 'materials', amount: 200 },
      { resource: 'food', amount: 100 },
    ],
    baseProduction: [{ resource: 'materials', amount: 20 }],
    unlockCondition: { type: 'never' },
  },
  {
    id: 'factory',
    name: 'Factory',
    description: 'Manufacture at a new scale.',
    category: 'materials',
    tier: 4,
    upgradeFrom: { unitId: 'workshop', amount: 5 },
    costs: [{ resource: 'materials', amount: 5000 }],
    baseProduction: [{ resource: 'materials', amount: 150 }],
    unlockCondition: { type: 'never' },
  },
  {
    id: 'thinker',
    name: 'Thinker',
    description: 'Turn curiosity into knowledge.',
    category: 'research',
    tier: 1,
    populationCost: 1,
    baseProduction: [{ resource: 'research', amount: 0.15 }],
    unlockCondition: { type: 'featureUnlocked', featureId: 'research' },
    legacyJobs: ['thinker'],
  },
  {
    id: 'scholar',
    name: 'Scholar',
    description: 'Bring five curious minds together for deeper study.',
    category: 'research',
    tier: 2,
    upgradeFrom: { unitId: 'thinker', amount: 5 },
    costs: [
      { resource: 'research', amount: 30 },
      { resource: 'materials', amount: 40 },
    ],
    baseProduction: [{ resource: 'research', amount: 1.2 }],
    unlockCondition: {
      type: 'technologyOwned',
      technologyId: 'knowledgeSharing',
    },
    visibilityCondition: { type: 'technologyOwned', technologyId: 'language' },
  },
  {
    id: 'scientist',
    name: 'Scientist',
    description: 'Develop systematic ways of understanding the world.',
    category: 'research',
    tier: 3,
    upgradeFrom: { unitId: 'scholar', amount: 4 },
    costs: [
      { resource: 'research', amount: 150 },
      { resource: 'materials', amount: 200 },
    ],
    baseProduction: [{ resource: 'research', amount: 6 }],
    unlockCondition: { type: 'never' },
  },
  {
    id: 'laboratory',
    name: 'Laboratory',
    description: 'Give Scientists a place to work together.',
    category: 'research',
    tier: 4,
    upgradeFrom: { unitId: 'scientist', amount: 5 },
    costs: [
      { resource: 'research', amount: 1000 },
      { resource: 'materials', amount: 3000 },
    ],
    baseProduction: [{ resource: 'research', amount: 45 }],
    effects: [
      {
        type: 'unitProductionMultiplier',
        unit: 'scientist',
        resource: 'research',
        value: 1.1,
      },
    ],
    unlockCondition: { type: 'never' },
  },
];
